name: Changes to Main Branch CI

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs:
  elixir-backend-job:
    name: Test Elixir Backend
    runs-on: ubuntu-latest
    services:
      db:
        image: postgres:11
        env:
          POSTGRES_USER: postgres
          POSTGRES_PASSWORD: postgres
          POSTGRES_DB: test_database
        ports:
          - 5432:5432
        options: --health-cmd pg_isready --health-interval 10s --health-timeout 5s --health-retries 5

    env:
      MIX_ENV: test
      GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

    steps:
      - uses: actions/checkout@v2
      - name: Set up Elixir
        uses: erlef/setup-elixir@885971a72ed1f9240973bd92ab57af8c1aa68f24
        with:
          elixir-version: "1.12.0"
          otp-version: "24"
      - name: Restore dependencies cache
        uses: actions/cache@v2
        with:
          path: deps
          key: ${{ runner.os }}-mix-${{ hashFiles('**/mix.lock') }}
          restore-keys: ${{ runner.os }}-mix-
      - name: Install dependencies
        run: mix deps.get
        working-directory: server
      - name: Run tests
        run: mix test
        working-directory: server

  get-workspace-packages:
    name: Yarn Workspaces Setup
    runs-on: ubuntu-latest
    env: 
      GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
    steps:
      - uses: actions/checkout@v2
      - name: Get packages in workspace
        uses: caffco/yarn-workspace-pacakges-github-action@v1.0.0
        with:
          repository_path: .

  common-package-test:
    needs: [get-workspace-packages]
    name: Common Package Test
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Set up Node
      - uses: actions/setup-node@v2
        with:
          node-version: '14'
      - name: Test common package
        run: yarn test
        working-directory: packages/common
  
  react-web-test:
    needs: [get-workspace-packages]
    name: React App Test
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Set up Node
      - uses: actions/setup-node@v2
        with:
          node-version: '14'
      - name: React App test
        run: yarn test
        working-directory: packages/web 
